// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI0k5IokPeoaMEQXBy9a4tjo5dYBzFqJo',
    appId: '1:914291213470:web:baada599bb4a2b7cc3278f',
    messagingSenderId: '914291213470',
    projectId: 'flashchat13-b09bc',
    authDomain: 'flashchat13-b09bc.firebaseapp.com',
    storageBucket: 'flashchat13-b09bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu3bCbq67ymLXWyxV1stiFnokBiu9Dtn4',
    appId: '1:914291213470:android:430ff4865ad046abc3278f',
    messagingSenderId: '914291213470',
    projectId: 'flashchat13-b09bc',
    storageBucket: 'flashchat13-b09bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPTy6v_VrFEWwgINqGxRqmAmEqkJ7IXSg',
    appId: '1:914291213470:ios:13637361da21e666c3278f',
    messagingSenderId: '914291213470',
    projectId: 'flashchat13-b09bc',
    storageBucket: 'flashchat13-b09bc.appspot.com',
    iosClientId: '914291213470-5douurcnl8hg13mgptklct2pe099bsqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPTy6v_VrFEWwgINqGxRqmAmEqkJ7IXSg',
    appId: '1:914291213470:ios:9c338768ba9bbbf8c3278f',
    messagingSenderId: '914291213470',
    projectId: 'flashchat13-b09bc',
    storageBucket: 'flashchat13-b09bc.appspot.com',
    iosClientId: '914291213470-di98n7p85hs35boip4svi6e09rlofutd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat2.RunnerTests',
  );
}
